---
- hosts: 10.1.0.5 
  become: yes 
  tasks: 
  - include_tasks: myfile.yml
  - name: copy file from master to node
    copy:
      src: mycopyfile
      dest: /home/maha/mycopyfile
  - name: install webserver
    apt:
      name: apache2
      state: present 