---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2 server
    apt:
      name: apache2
      state: prsent
  - name: i want to start webserver
    service:
      name: apache2
      state: started